services:
  - name: keycloak
    env: docker
    dockerfile_path: Dockerfile
    plan: starter # Or choose the appropriate plan
    env_vars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        value: "jdbc:postgresql://keycloak_871l_user:WUNfz0PsMctOWHtAciLLz1p4zP5HISav@dpg-co44tgcf7o1s738ojaug-a.oregon-postgres.render.com:5432/keycloak_871l"
      - key: KC_DB_USERNAME
        value: keycloak_871l_user
      - key: KC_DB_PASSWORD
        value: WUNfz0PsMctOWHtAciLLz1p4zP5HISav
    ports:
      - 8443

